import os

def inject(timestamp):
    base = os.path.join("deliverables", f"run_{timestamp}")
    os.makedirs(base, exist_ok=True)

    with open(os.path.join(base, ".env.template"), "w") as f:
        f.write("GROQ_API_KEY=your-groq-key-here\nOPENAI_API_KEY=your-openai-key-here\nFORGE_MODE=production\n")

    with open(os.path.join(base, "pyproject.toml"), "w") as f:
        f.write("""[project]
name = "agentic_forge"
version = "0.1.0"
description = "Portable agentic workforce generated by the Forge"
authors = ["RWV Techsolutions"]
dependencies = ["crewai", "openai", "pyyaml", "rich"]
requires-python = ">=3.9"
""")